question_data = [
    {"text": "파이썬은 인터프리터 언어이다.", "answer": "True"},
    {"text": "지구는 태양계에서 가장 큰 행성이다.", "answer": "False"},
    {"text": "대한민국의 수도는 서울이다.", "answer": "True"},
    {"text": "물의 화학식은 H2O이다.", "answer": "True"},
    {"text": "에베레스트 산은 바다의 가장 깊은 지점보다 낮다.", "answer": "False"},
    {"text": "빛은 소리보다 빠르다.", "answer": "True"},
    {"text": "컴퓨터는 1진수로 작동한다.", "answer": "False"},
    {"text": "포유류는 모두 포유강에 속한다.", "answer": "True"},
    {"text": "달에는 대기가 없다.", "answer": "True"},
    {"text": "1미터는 100센티미터이다.", "answer": "True"},
]

question_data = {"response_code": 0,
       "results": [
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "Tennis was once known as Racquetball.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "The Olympics tennis court is a giant green screen.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "Skateboarding was included in the 2020 Summer Olympics in Tokyo.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"type": "boolean", "difficulty": "easy", "category": "Sports",
            "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"type": "boolean", "difficulty": "medium", "category": "Sports",
            "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"type": "boolean", "difficulty": "easy", "category": "Sports",
            "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"type": "boolean", "difficulty": "easy", "category": "Sports",
            "question": "Peyton Manning retired after winning Super Bowl XLIX.", "correct_answer": "False",
            "incorrect_answers": ["True"]}]}